In [14]:
import pandas as pd
import numpy as np

## **Clarity Monitors**

In [15]:
# Load the dataset from a CSV file
hourly_df = pd.read_csv('../data/Hourly Clarity Data 1-24 to 1-25.csv')
hourly_df.head()

,datasourceId,sourceId,sourceType,outputFrequency,startOfPeriod,endOfPeriod,locationLatitude,locationLongitude,atmPressure1HourMean.raw,atmPressure1HourMean.status,...,temperatureAmbient1HourMean.value,temperatureInternal1HourMean.raw,temperatureInternal1HourMean.status,temperatureInternal1HourMean.value,windDirection1HourMean.raw,windDirection1HourMean.status,windDirection1HourMean.value,windSpeed1HourMean.raw,windSpeed1HourMean.status,windSpeed1HourMean.value
0,DHSHV3008,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T17:00:00.000Z,2024-10-30T18:00:00.000Z,37.65544,122.41276,NaN,NaN,...,NaN,17.62,sensor-ready,17.62,NaN,NaN,NaN,NaN,NaN,NaN
1,DHSHV3008,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T18:00:00.000Z,2024-10-30T19:00:00.000Z,37.65544,122.41276,NaN,NaN,...,NaN,19.62,sensor-ready,19.62,NaN,NaN,NaN,NaN,NaN,NaN
2,DHSHV3008,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T19:00:00.000Z,2024-10-30T20:00:00.000Z,37.65544,122.41276,NaN,NaN,...,NaN,21.16,sensor-ready,21.16,NaN,NaN,NaN,NaN,NaN,NaN
3,DHSHV3008,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T20:00:00.000Z,2024-10-30T21:00:00.000Z,37.65544,122.41276,NaN,NaN,...,NaN,21.36,sensor-ready,21.36,NaN,NaN,NaN,NaN,NaN,NaN
4,DHSHV3008,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T21:00:00.000Z,2024-10-30T22:00:00.000Z,37.65544,122.41276,NaN,NaN,...,NaN,20.79,sensor-ready,20.79,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
hourly_df.shape

(19383, 110)

In [17]:
# Load location data for clarity monitors
location_df = pd.read_csv('../data/risesouthcity_locations.csv')
location_df.head()

  Datasource ID                              Name
0     DHSHV3008            Rise South City Office
1     DJGNN5114  San Bruno School District Office
2     DVRGV9737                     Gardiner Park
3     DRCAC7970                  Belle Air School
4     DCVIM2201                    Brentwood Park

In [18]:
location_df.shape

(14, 2)

In [19]:
# Join the two dataframes on the ID column
joined_df = pd.merge(hourly_df, location_df, left_on='datasourceId', right_on='Datasource ID')
joined_df.drop(columns=['datasourceId'], inplace=True)
joined_df.head()

,sourceId,sourceType,outputFrequency,startOfPeriod,endOfPeriod,locationLatitude,locationLongitude,atmPressure1HourMean.raw,atmPressure1HourMean.status,atmPressure1HourMean.value,...,temperatureInternal1HourMean.status,temperatureInternal1HourMean.value,windDirection1HourMean.raw,windDirection1HourMean.status,windDirection1HourMean.value,windSpeed1HourMean.raw,windSpeed1HourMean.status,windSpeed1HourMean.value,Datasource ID,Name
0,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T17:00:00.000Z,2024-10-30T18:00:00.000Z,37.65544,122.41276,NaN,NaN,NaN,...,sensor-ready,17.62,NaN,NaN,NaN,NaN,NaN,NaN,DHSHV3008,Rise South City Office
1,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T18:00:00.000Z,2024-10-30T19:00:00.000Z,37.65544,122.41276,NaN,NaN,NaN,...,sensor-ready,19.62,NaN,NaN,NaN,NaN,NaN,NaN,DHSHV3008,Rise South City Office
2,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T19:00:00.000Z,2024-10-30T20:00:00.000Z,37.65544,122.41276,NaN,NaN,NaN,...,sensor-ready,21.16,NaN,NaN,NaN,NaN,NaN,NaN,DHSHV3008,Rise South City Office
3,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T20:00:00.000Z,2024-10-30T21:00:00.000Z,37.65544,122.41276,NaN,NaN,NaN,...,sensor-ready,21.36,NaN,NaN,NaN,NaN,NaN,NaN,DHSHV3008,Rise South City Office
4,AMMHPRJX,CLARITY_NODE,hour,2024-10-30T21:00:00.000Z,2024-10-30T22:00:00.000Z,37.65544,122.41276,NaN,NaN,NaN,...,sensor-ready,20.79,NaN,NaN,NaN,NaN,NaN,NaN,DHSHV3008,Rise South City Office

In [20]:
# Look for all columns with 'no2' or 'pm25' in their names
no2_columns = [col for col in joined_df.columns if 'no2' in col.lower()]
pm25_columns = [col for col in joined_df.columns if 'pm2_5' in col.lower()]
# Print the columns found
print("NO2 Columns:", no2_columns)
print("PM2.5 Columns:", pm25_columns)

NO2 Columns: ['no2Conc1HourMean.raw', 'no2Conc1HourMean.status', 'no2Conc1HourMean.value', 'no2Conc1HourMeanUsEpaAqi.raw', 'no2Conc1HourMeanUsEpaAqi.status', 'no2Conc1HourMeanUsEpaAqi.value', 'no2Conc1HourMeanWaDwerAqi.raw', 'no2Conc1HourMeanWaDwerAqi.status', 'no2Conc1HourMeanWaDwerAqi.value']
PM2.5 Columns: ['pm2_5ConcMass1HourMean.raw', 'pm2_5ConcMass1HourMean.status', 'pm2_5ConcMass1HourMean.value', 'pm2_5ConcMass1HourMeanWaDwerAqi.raw', 'pm2_5ConcMass1HourMeanWaDwerAqi.status', 'pm2_5ConcMass1HourMeanWaDwerAqi.value', 'pm2_5ConcMass24HourRollingMean.raw', 'pm2_5ConcMass24HourRollingMean.status', 'pm2_5ConcMass24HourRollingMean.value', 'pm2_5ConcMassNowcast.raw', 'pm2_5ConcMassNowcast.status', 'pm2_5ConcMassNowcast.value', 'pm2_5ConcMassNowcastUsEpaAqi.raw', 'pm2_5ConcMassNowcastUsEpaAqi.status', 'pm2_5ConcMassNowcastUsEpaAqi.value', 'pm2_5ConcNum1HourMean.raw', 'pm2_5ConcNum1HourMean.status', 'pm2_5ConcNum1HourMean.value', 'pm2_5ConcNum24HourRollingMean.raw', 'pm2_5ConcNum24HourRollingMean.status', 'pm2_5ConcNum24HourRollingMean.value']

In [21]:
# Filter the dataframe to include only the columns of interest
joined_df = joined_df[['startOfPeriod', 'Name', 'Datasource ID', 'locationLatitude', 'locationLongitude']
                       + no2_columns + pm25_columns]
joined_df.head()

,startOfPeriod,Name,Datasource ID,locationLatitude,locationLongitude,no2Conc1HourMean.raw,no2Conc1HourMean.status,no2Conc1HourMean.value,no2Conc1HourMeanUsEpaAqi.raw,no2Conc1HourMeanUsEpaAqi.status,...,pm2_5ConcMassNowcast.value,pm2_5ConcMassNowcastUsEpaAqi.raw,pm2_5ConcMassNowcastUsEpaAqi.status,pm2_5ConcMassNowcastUsEpaAqi.value,pm2_5ConcNum1HourMean.raw,pm2_5ConcNum1HourMean.status,pm2_5ConcNum1HourMean.value,pm2_5ConcNum24HourRollingMean.raw,pm2_5ConcNum24HourRollingMean.status,pm2_5ConcNum24HourRollingMean.value
0,2024-10-30T17:00:00.000Z,Rise South City Office,DHSHV3008,37.65544,122.41276,-30.55,calibration-mixed,1.46,NaN,calibration-mixed,...,39.03,152.0,calibrated-ready,110.0,37.40,sensor-ready,37.40,71.04,sensor-ready,71.04
1,2024-10-30T18:00:00.000Z,Rise South City Office,DHSHV3008,37.65544,122.41276,-47.38,calibration-error,NaN,NaN,calibration-error,...,30.68,122.0,calibrated-ready,91.0,40.56,sensor-ready,40.56,60.88,sensor-ready,60.88
2,2024-10-30T19:00:00.000Z,Rise South City Office,DHSHV3008,37.65544,122.41276,-54.26,calibration-error,NaN,NaN,calibration-error,...,32.42,115.0,calibrated-ready,94.0,46.88,sensor-ready,46.88,57.38,sensor-ready,57.38
3,2024-10-30T20:00:00.000Z,Rise South City Office,DHSHV3008,37.65544,122.41276,-31.63,calibration-error,NaN,NaN,calibration-error,...,28.88,100.0,calibrated-ready,88.0,34.23,sensor-ready,34.23,52.75,sensor-ready,52.75
4,2024-10-30T21:00:00.000Z,Rise South City Office,DHSHV3008,37.65544,122.41276,-29.13,calibration-mixed,1.70,NaN,calibration-mixed,...,20.68,80.0,calibrated-ready,72.0,22.57,sensor-ready,22.57,47.72,sensor-ready,47.72

In [22]:
# Convert the 'startOfPeriod' column to datetime
joined_df['startOfPeriod'] = pd.to_datetime(joined_df['startOfPeriod'])
joined_df['startOfPeriod'].dtype

datetime64[ns, UTC]

In [31]:
# Update the no2_columns list to include only columns with 'value' in their names or 'EPAAqi'
no2_columns = [col for col in no2_columns if'WaDwer' not in col and 'value' in col]

# Update the pm25_columns list to include only columns with 'value' in their names or 'EPAAqi'
pm25_columns = [col for col in pm25_columns if 'WaDwer' not in col and 'Mass' in col and 'value' in col]

# Print the updated lists
print("Updated NO2 Columns:", no2_columns)
print("Updated PM2.5 Columns:", pm25_columns)

Updated NO2 Columns: ['no2Conc1HourMean.value', 'no2Conc1HourMeanUsEpaAqi.value']
Updated PM2.5 Columns: ['pm2_5ConcMass1HourMean.value', 'pm2_5ConcMass24HourRollingMean.value', 'pm2_5ConcMassNowcast.value', 'pm2_5ConcMassNowcastUsEpaAqi.value']

In [32]:
# Filter dataframe with updated columns and location/time columns
joined_df = joined_df[['startOfPeriod', 'Name', 'Datasource ID', 'locationLatitude', 'locationLongitude']
                       + no2_columns + pm25_columns]

joined_df.columns

Index(['startOfPeriod', 'Name', 'Datasource ID', 'locationLatitude',
       'locationLongitude', 'no2Conc1HourMean.value',
       'no2Conc1HourMeanUsEpaAqi.value', 'pm2_5ConcMass1HourMean.value',
       'pm2_5ConcMass24HourRollingMean.value', 'pm2_5ConcMassNowcast.value',
       'pm2_5ConcMassNowcastUsEpaAqi.value'],
      dtype='object')

In [ ]:
# Drop Nowcast column for PM2.5 value
joined_df.drop(columns=['pm2_5ConcMassNowcast.value'], inplace=True)

# Change column names to more readable format
joined_df.rename(columns={
    'startOfPeriod': 'time',
    'Name': 'location_name',
    'Datasource ID': 'location_id',
    'locationLatitude': 'latitude',
    'locationLongitude': 'longitude',
    'no2Conc1HourMean.value': 'no2_1h_mean',
    'no2Conc1HourMeanUsEpaAqi.value': 'no2_1h_mean_aqi',
    'pm2_5ConcMass1HourMean.value': 'pm2_5_1h_mean',
    'pm2_5ConcMassNowcastUsEpaAqi.value': 'pm2_5_1h_mean_aqi',
    'pm2_5ConcMass24HourRollingMean.value': 'pm2_5_24h_mean',
}, inplace=True)

joined_df.head()

,time,location_name,location_id,latitude,longitude,no2_1h_mean,no2_1h_mean_aqi,pm2_5_1h_mean,pm2_5_24h_mean,pm2_5_1h_mean_aqi
0,2024-10-30 17:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,1.46,1.0,25.65,45.72,110.0
1,2024-10-30 18:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,NaN,NaN,24.42,38.62,91.0
2,2024-10-30 19:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,NaN,NaN,33.93,37.45,94.0
3,2024-10-30 20:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,NaN,NaN,25.57,35.07,88.0
4,2024-10-30 21:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,1.70,1.0,12.74,31.35,72.0

In [34]:
# Find any missing values in the dataframe
missing_values = joined_df.isnull().sum()
missing_values[missing_values > 0]

no2_1h_mean          4932
no2_1h_mean_aqi      4932
pm2_5_1h_mean         165
pm2_5_1h_mean_aqi     193
dtype: int64

In [35]:
joined_df.shape

(19383, 10)

In [37]:
# Impute missing values using forward fill followed by backward fill because of time-series data
joined_df.ffill(inplace=True)
joined_df.bfill(inplace=True)

# Check for any remaining missing values
missing_values = joined_df.isnull().sum()
missing_values[missing_values > 0]

Series([], dtype: int64)

In [38]:
# Check dataframe before saving
joined_df.head()

,time,location_name,location_id,latitude,longitude,no2_1h_mean,no2_1h_mean_aqi,pm2_5_1h_mean,pm2_5_24h_mean,pm2_5_1h_mean_aqi
0,2024-10-30 17:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,1.46,1.0,25.65,45.72,110.0
1,2024-10-30 18:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,1.46,1.0,24.42,38.62,91.0
2,2024-10-30 19:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,1.46,1.0,33.93,37.45,94.0
3,2024-10-30 20:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,1.46,1.0,25.57,35.07,88.0
4,2024-10-30 21:00:00+00:00,Rise South City Office,DHSHV3008,37.65544,122.41276,1.70,1.0,12.74,31.35,72.0

In [39]:
# Save the cleaned dataframe to a new CSV file
joined_df.to_csv('../data/clarity_cleaned_hourly_data.csv', index=False)

In [ ]:
# Script to clean Clarity hourly data
import pandas as pd

def clean_clarity_data(hourly_file_path, location_file_path, output_file_path):
    # Load the datasets
    hourly_df = pd.read_csv(hourly_file_path)
    location_df = pd.read_csv(location_file_path)

    # Join the two dataframes on the ID column
    joined_df = pd.merge(hourly_df, location_df, left_on='datasourceId', right_on='Datasource ID')
    joined_df.drop(columns=['datasourceId'], inplace=True)

    # Identify NO2 and PM2.5 columns
    no2_columns = [col for col in joined_df.columns if 'no2' in col.lower()]
    pm25_columns = [col for col in joined_df.columns if 'pm2_5' in col.lower()]

    # Filter the dataframe to include only the columns of interest
    joined_df = joined_df[['startOfPeriod', 'Name', 'Datasource ID', 'locationLatitude', 'locationLongitude']
                           + no2_columns + pm25_columns]

    # Convert the 'startOfPeriod' column to datetime
    joined_df['startOfPeriod'] = pd.to_datetime(joined_df['startOfPeriod'])

    # Update the NO2 and PM2.5 columns to include only relevant ones
    no2_columns = [col for col in no2_columns if 'value' in col and 'WaDwer' not in col]
    pm25_columns = [col for col in pm25_columns if 'value' in col and 'WaDwer' not in col and 'Mass' in col]

    # Filter dataframe with updated columns and location/time columns
    joined_df = joined_df[['startOfPeriod', 'Name', 'Datasource ID', 'locationLatitude', 'locationLongitude']
                           + no2_columns + pm25_columns]

    # Rename columns to more readable format
    joined_df.rename(columns={
        'startOfPeriod': 'time',
        'Name': 'location_name',
        'Datasource ID': 'location_id',
        'locationLatitude': 'latitude',
        'locationLongitude': 'longitude',
        'no2Conc1HourMean.value': 'no2_1h_mean',
        'no2Conc1HourMeanUsEpaAqi.value': 'no2_1h_mean_aqi',
        'pm2_5ConcMass1HourMean.value': 'pm2_5_1h_mean',
        'pm2_5ConcMassNowcastUsEpaAqi.value': 'pm2_5_1h_mean_aqi',
        'pm2_5ConcMass24HourRollingMean.value': 'pm2_5_24h_mean',
    }, inplace=True)

    # Drop unnecessary columns
    if 'pm2_5_nowcast' in joined_df.columns:
        joined_df.drop(columns=['pm2_5_nowcast'], inplace=True)

    # Impute missing values using forward fill followed by backward fill
    joined_df.ffill(inplace=True)
    joined_df.bfill(inplace=True)

    # Save the cleaned dataframe to a new CSV file
    joined_df.to_csv(output_file_path, index=False)